### ISSUE TITLE
[feat] 메인 제품 카테고리 목록 조회 API 구현

### ISSUE THREAD

**Issue by Hong0329** [DO-SOPT-CDS-SEMINAR/Apple-Server#11]
## 🚀 About Issue 🚀

메인 제품 카테고리 목록 조회 API 구현
```
/main/category
``` 
## ✅ Todo 

- [ ] 카테고리 도메인 설계
- [ ] 메인 컨트롤러 구현
- [ ] 메인 서비스 로직 구현
- [ ] 메인 레포지토리 구현

##Image
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/c81c67c4-a906-4968-af93-92da13ab0b02)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/e0e072c4-a866-4aff-ab1d-211238d7bcb1)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/921f79e5-91f5-47be-b130-1689ec3f18be)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/ff0c1934-66f7-46c7-986a-a8ffbe2e7b1e)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/e962b6e2-d67b-4675-8d12-8b0dc5cf2fd7)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/4415f7c8-a997-4a06-b8d8-d16a42decc97)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/796e612e-5aa7-4b10-8587-c9310d39dd78)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/3e4d75d0-871a-4d7d-8972-7d580ec5bf96)
