### ISSUE TITLE
[feat] 메인 뷰 내의 모든 제품 정보 조회 API 구현

### ISSUE THREAD

**Issue by Hong0329** [DO-SOPT-CDS-SEMINAR/Apple-Server#12]
## 🚀 About Issue 🚀

메인 뷰 내의 모든 제품 정보 조회 API 구현
```
/main/items
``` 
## ✅ Todo 

- [ ] 메인뷰아이템 도메인 설계
- [ ] 메인  컨트롤러 수정
- [ ] 메인  서비스 수정
- [ ] 메인 아이템 레포지토리 구현

## Image
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/210476aa-5d92-4de9-9c25-f77b0b94d731)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/abd1518a-3489-401b-992c-6f5e14edf816)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/2ba8770e-f0a9-4dcf-b700-049bd5d624a4)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/372e4c3f-94b3-48b4-9e50-1443aee0547a)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/74b1b4b0-35d9-48f5-b377-98bb6e2834e5)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/a7b1ddb6-4227-46c8-9aa7-e0a03c116286)
## Image2
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/b8e73219-1238-44ed-9b0e-0cebae1753ea)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/cde6936b-18b2-4606-bb06-80f85cc9480e)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/ebff8f70-c360-4dcd-8a5a-eacf867f3d16)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/81ee024a-7fe5-48fa-91c9-9b311073be8a)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/7005ea9f-2d76-4980-93dd-9381539ecf62)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/15102d1d-0db3-4602-8937-3023de43cf43)
## Image3
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/55f63321-70ba-4a09-ade9-0009775659fb)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/77a4a0e5-3255-40a5-8e96-85f8643e8fa5)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/5a228397-bd3f-478e-ac0d-e288d510fad3)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/5ec35915-b1e1-4a82-aad7-e832d752e31b)
## Image3
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/d460dc69-4a9a-4d5a-9e1c-d44d3feef631)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/78cdb8da-c690-44d8-aead-81c1073e5214)
![image](https://github.com/DO-SOPT-CDS-SEMINAR/Apple-Server/assets/97835512/593f8f22-763b-4ef3-9e54-f8c2464b5447)
