### ISSUE TITLE
[feat] 하단 안내 문구 조회 API 구현

### ISSUE THREAD

**Issue by Hong0329** [DO-SOPT-CDS-SEMINAR/Apple-Server#13]
## 🚀 About Issue 🚀

하단 안내 문구 조회 API 구현
```
/main/information
``` 
## ✅ Todo 

- [ ] 메인 인포메이셔 도메인 설계
- [ ] 메인 컨트롤러 구현
- [ ] 메인 서비스 구현
- [ ] 메인 레포지토리 구현
