### ISSUE TITLE
[feat] 제품 구입하기 이미지 조회 API 구현

### ISSUE THREAD

**Issue by ChaeAg** [DO-SOPT-CDS-SEMINAR/Apple-Server#17]
## 🚀 About Issue 🚀
제품 구입하기 이미지 조회 `GET` API 구현
```
/product/{productId}/images
``` 

## ✅ Todo 
- [x] 제품 구입하기 이미지 도메인 설계
- [x] `ProductController`에 API 구현
- [x] `ProductService`에 제품 구입하기 이미지 조회 로직 구현
