### ISSUE TITLE
[feat] 제품 목록 조회 API 구현

### ISSUE THREAD

**Issue by ChaeAg** [DO-SOPT-CDS-SEMINAR/Apple-Server#4]
## 🚀 About Issue 🚀
제품 타입에 맞는 제품 목록을 조회하는  `GET`  API 구현
```
/product/{productType}/items
``` 

## ✅ Todo 
- [ ] 제품 도메인 설계
- [ ] 제품 컨트롤러 구현
- [ ] 제품 서비스 로직 구현
- [ ] 제품 레포지토리 구현
