### ISSUE TITLE
[feat] 아이패드 뷰 내의 모든 제품 정보 조회 API 구현

### ISSUE THREAD

**Issue by ChaeAg** [DO-SOPT-CDS-SEMINAR/Apple-Server#5]
## 🚀 About Issue 🚀
아이패드뷰 내에 있는 전체 제품의 정보를 조회하는  `GET`  API 구현
```
/ipad/items
``` 

## ✅ Todo 
- [ ] 아이패드뷰 아이템 도메인 설계
- [ ] 아이패드뷰 아이템 컨트롤러 구현
- [ ] 아이패드뷰 아이템 서비스 로직 구현
- [ ] 아이패드뷰 아이템 레포지토리 구현
